server:
  port: 8089
spring:
  datasource:
    username: sa
    password: password
    url: jdbc:mysql://mysql-standalone:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  
